app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/home/peeps-uuids
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.6
  ports:
    - "5432"
