version: "3.3"

networks:
#  front:
  back:

services:
  app:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000"
    depends_on:
      - db
    networks:
      back:
    environment:
      SECRET_KEY_BASE: 1234
      DATABASE_URL: postgres://postgres:postgres@db/peeps_uuids

  db:
    image: postgres:12.1
    ports:
      - "5432"
    networks:
      back:
